# overlays/dev/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Este será el nombre del Secret de Kubernetes generado
  name: db-credentials
spec:
  # Referencia al store que creamos antes
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    # Define cómo se debe llamar el Secret de k8s
    name: db-credentials
  data:
  - secretKey: password # La "key" que espera nuestro deployment.yaml
    remoteRef:
      key: dev/mi-app-nodejs/db-credentials # El nombre del secreto en AWS Secrets Manager

